/// A case category as shown on the setup screen.
class CaseCategory {
  const CaseCategory({
    required this.id,
    required this.name,
    required this.emoji,
  });

  factory CaseCategory.fromJson(Map<String, dynamic> json) => CaseCategory(
        id: json['id'] as String,
        name: json['name'] as String,
        emoji: json['emoji'] as String? ?? '🗂️',
      );

  final String id;
  final String name;
  final String emoji;
}

/// A single mystery: either loaded from `assets/cases.json` or generated by AI.
class MysteryCase {
  const MysteryCase({
    required this.id,
    required this.category,
    required this.title,
    required this.description,
    required this.clues,
    required this.questions,
    this.aiGenerated = false,
  });

  factory MysteryCase.fromJson(
    Map<String, dynamic> json, {
    bool aiGenerated = false,
  }) {
    List<String> strings(Object? value) => switch (value) {
          final List<dynamic> list =>
            list.map((e) => e.toString().trim()).where((e) => e.isNotEmpty).toList(),
          _ => const <String>[],
        };

    return MysteryCase(
      id: json['id']?.toString() ?? 'case_${DateTime.now().microsecondsSinceEpoch}',
      category: json['category']?.toString() ?? 'general',
      title: json['title']?.toString().trim() ?? 'قضية بلا عنوان',
      description: json['description']?.toString().trim() ?? '',
      clues: strings(json['clues']),
      questions: strings(json['questions']),
      aiGenerated: aiGenerated,
    );
  }

  final String id;
  final String category;
  final String title;
  final String description;

  /// The three facts only the Silent Witness gets to read.
  final List<String> clues;

  /// Suggested interrogation questions on the detective's card.
  final List<String> questions;

  final bool aiGenerated;

  /// A case is playable only if it carries a title and at least one clue.
  bool get isUsable => title.isNotEmpty && clues.isNotEmpty;
}
